name: Builder
on:    
  workflow_dispatch:
   

jobs:  
  # ==============================================================================
  # =                               WINDOWS                                      =
  # ==============================================================================
  windows-build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - if: runner.os == 'Windows'
      name: "Install mingw deps"
      uses: msys2/setup-msys2@v2
      with:
          install: make autoconf automake libtool mingw-w64-x86_64-gcc libtool mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-dlfcn mingw-w64-x86_64-grep  mingw-w64-x86_64-curl unzip
          update: false

    - name: Download PureData
      run: choco install puredata --yes
        
    - if: runner.os == 'Windows'
      name: Build py4pd
      shell: msys2 {0}
      run: |
        make extension=m_amd64 
    
    - name: Upload Object 
      uses: actions/upload-artifact@v3
      with:
        name: percolate
        path: .


  # ==============================================================================
  # =                               MAC ARM                                      =
  # ==============================================================================
  macos-build:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install PureData
      run: |
        brew install --cask pd

    - name: Build
      run: | 
        make extension=d_arm64
        make extension=d_amd64

    - name: Upload Object
      uses: actions/upload-artifact@v3
      with:
        name: percolate
        path: ./


  # ==============================================================================
  # =                               LINUX                                        =
  # ==============================================================================

  linux-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
  
      - name: Install PureData
        run: |
          sudo add-apt-repository ppa:pure-data/pure-data
          sudo apt-get update
          sudo apt-get install puredata -y

      - name: Build
        run: make PDINCLUDEDIR=./pure-data/src/ extension=l_amd64 
          
      - name: Upload Object
        uses: actions/upload-artifact@v3
        with:
          name: percolate
          path: ./

